# Generated by Django 4.1.3 on 2022-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("family", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("SW", "Sport wear"),
                            ("OW", "Outwear"),
                        ],
                        max_length=2,
                    ),
                ),
                ("address", models.TextField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("P", "primary"), ("S", "secondary"), ("D", "danger")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
