# Generated by Django 4.1.3 on 2022-11-30 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="name", new_name="title",
        ),
        migrations.AddField(
            model_name="product", name="price", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(14),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                choices=[
                    ("Tehran", "Tehran"),
                    ("Shiraz", "Shiraz"),
                    ("Tabriz", "Tabriz"),
                    ("Mashhad", "Mashhad"),
                    ("Esfehan", "Esfehan"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product", name="image", field=models.ImageField(upload_to=""),
        ),
    ]
