# Generated by Django 4.1.3 on 2022-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
