# Generated by Django 4.1.3 on 2022-12-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail", name="date", field=models.DateField(null=True),
        ),
    ]
